defaults: &defaults
  layout: 'application'
#  job_temp_dir: '/tmp' # uses system temp dir by default

development:
  <<: *defaults
  fits_path: '/home/qgkb58/hydra/fits-0.8.6/fits.sh'

test:
  <<: *defaults

production:
  <<: *defaults
