defaults: &defaults
  layout: 'application'
  identifier_template: 'ba.reeddeeddk'
  identifier_statefile: '/tmp/oubliette-minter-state'
  notification_email_from: 'oubliette@durham.ac.uk'
  notification_email_to: []

development:
  <<: *defaults
  # Disable cross site request forgery checks
  # disable_csrf: true
  # This lets anyone in with full access as long as api_debug request parameter
  # is set. Only for development or debugging.
  api_debug: true

test:
  <<: *defaults

production:
  <<: *defaults
