defaults: &defaults
  layout: 'application'
  identifier_template: 's0.reeddeeddk'
  identifier_statefile: '/tmp/schmit-minter-state'
  notification_email_from: 'schmit@durham.ac.uk'
  notification_email_to: []
#  job_temp_dir: '/tmp' # uses system temp dir by default

development:
  <<: *defaults
  ark_naan: '12345'
  notification_email_to: []
  wip_feed_id: :first
  primo_config:
    local_copy: true
    root: <%= File.join(Dir.home,'mock_primo') %>/
  xtf_config:
    local_copy: true
    create_dirs: true
#    root: <%= File.join(Dir.home,'mock_xtf') %>/
#    redirect_root: <%= File.join(Dir.home,'mock_xtf') %>/redirect/
    root: /home/qgkb58/library/xtf/data/ark/
    redirect_root: /home/qgkb58/library/xtf/data/redirect/
    public_url_base: 'http://localhost/xtf/view?docId='
    

test:
  <<: *defaults
  wip_feed_id: :first

production:
  <<: *defaults
