defaults: &defaults
#  job_temp_dir: '/tmp' # uses system temp dir by default
  layout: 'application'
  identifier_template: 't0.reeddeeddk'
  identifier_statefile: '/tmp/trifle-minter-state'
  image_convert_command: ['trifle_scripts/convert_ptif.sh']
  image_convert_format: 'ptif'

development:
  <<: *defaults
  fits_path: '/home/qgkb58/hydra/fits-0.8.6/fits.sh'
  ark_naan: '12345'
  allowed_ark_naan: ['12345','11111']
  image_server_url: 'http://localhost/iipsrv/iipsrv.fcgi'
  image_service_url: 'http://localhost/iipsrv/iipsrv.fcgi?IIIF='
  published_iiif_url: 'http://localhost/iiif/'
  iiif_host: 'http://localhost:3000'
  mirador_location: 'Durham University'
  mirador_base_url: 'http://localhost/mirador/'
  api_debug: true
  image_convert_command: ['trifle_scripts/convert_jp2.sh']
  image_size_command: ['trifle_scripts/image_size_jp2.sh']
  image_convert_format: 'jp2'
  image_server_config:
    local_copy: true
    file_permissions: 0644
    #host: 'localhost'
    #user: <%= ENV['USER'] %>
    iiif_root: <%= File.join(Dir.home,'mock_iiif') %>/
    images_root: <%= File.join(Dir.home,'iipimages') %>/
    create_dirs: true

test:
  <<: *defaults

production:
  <<: *defaults
