require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Hilda::IngestionProcessesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # IngestionProcess. As you add validations to IngestionProcess, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # IngestionProcessesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all ingestion_processes as @ingestion_processes" do
      ingestion_process = IngestionProcess.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:ingestion_processes)).to eq([ingestion_process])
    end
  end

  describe "GET #show" do
    it "assigns the requested ingestion_process as @ingestion_process" do
      ingestion_process = IngestionProcess.create! valid_attributes
      get :show, {:id => ingestion_process.to_param}, valid_session
      expect(assigns(:ingestion_process)).to eq(ingestion_process)
    end
  end

  describe "GET #new" do
    it "assigns a new ingestion_process as @ingestion_process" do
      get :new, {}, valid_session
      expect(assigns(:ingestion_process)).to be_a_new(IngestionProcess)
    end
  end

  describe "GET #edit" do
    it "assigns the requested ingestion_process as @ingestion_process" do
      ingestion_process = IngestionProcess.create! valid_attributes
      get :edit, {:id => ingestion_process.to_param}, valid_session
      expect(assigns(:ingestion_process)).to eq(ingestion_process)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new IngestionProcess" do
        expect {
          post :create, {:ingestion_process => valid_attributes}, valid_session
        }.to change(IngestionProcess, :count).by(1)
      end

      it "assigns a newly created ingestion_process as @ingestion_process" do
        post :create, {:ingestion_process => valid_attributes}, valid_session
        expect(assigns(:ingestion_process)).to be_a(IngestionProcess)
        expect(assigns(:ingestion_process)).to be_persisted
      end

      it "redirects to the created ingestion_process" do
        post :create, {:ingestion_process => valid_attributes}, valid_session
        expect(response).to redirect_to(IngestionProcess.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved ingestion_process as @ingestion_process" do
        post :create, {:ingestion_process => invalid_attributes}, valid_session
        expect(assigns(:ingestion_process)).to be_a_new(IngestionProcess)
      end

      it "re-renders the 'new' template" do
        post :create, {:ingestion_process => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ingestion_process" do
        ingestion_process = IngestionProcess.create! valid_attributes
        put :update, {:id => ingestion_process.to_param, :ingestion_process => new_attributes}, valid_session
        ingestion_process.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested ingestion_process as @ingestion_process" do
        ingestion_process = IngestionProcess.create! valid_attributes
        put :update, {:id => ingestion_process.to_param, :ingestion_process => valid_attributes}, valid_session
        expect(assigns(:ingestion_process)).to eq(ingestion_process)
      end

      it "redirects to the ingestion_process" do
        ingestion_process = IngestionProcess.create! valid_attributes
        put :update, {:id => ingestion_process.to_param, :ingestion_process => valid_attributes}, valid_session
        expect(response).to redirect_to(ingestion_process)
      end
    end

    context "with invalid params" do
      it "assigns the ingestion_process as @ingestion_process" do
        ingestion_process = IngestionProcess.create! valid_attributes
        put :update, {:id => ingestion_process.to_param, :ingestion_process => invalid_attributes}, valid_session
        expect(assigns(:ingestion_process)).to eq(ingestion_process)
      end

      it "re-renders the 'edit' template" do
        ingestion_process = IngestionProcess.create! valid_attributes
        put :update, {:id => ingestion_process.to_param, :ingestion_process => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested ingestion_process" do
      ingestion_process = IngestionProcess.create! valid_attributes
      expect {
        delete :destroy, {:id => ingestion_process.to_param}, valid_session
      }.to change(IngestionProcess, :count).by(-1)
    end

    it "redirects to the ingestion_processes list" do
      ingestion_process = IngestionProcess.create! valid_attributes
      delete :destroy, {:id => ingestion_process.to_param}, valid_session
      expect(response).to redirect_to(ingestion_processes_url)
    end
  end

end
