source 'https://rubygems.org'

# Declare your gem's dependencies in hilda_durham.gemspec.
# Bundler will treat runtime dependencies like base dependencies, and
# development dependencies will be added by default to the :development group.
gemspec

gem 'hilda', path: File.expand_path("../..", __FILE__)
gem 'schmit_api', path: File.expand_path('../../../schmit/schmit_api', __FILE__)

test_app_gemfile_path = File.expand_path("../test_app/Gemfile", __FILE__)
if File.exists?(test_app_gemfile_path)
  instance_eval (File.read(test_app_gemfile_path).lines.select do |line|
    !(line.index('hilda') || line.index('schmit') || line.index('source'))
  end).join("\n")
end
